import type { AppConfig, BrandProfile } from "../config.js";
import type { DocumentAsset, DocumentBlock, DocumentModel, RichTextSpan } from "../model/document.js";

// ── Colours (no leading #) ────────────────────────────────────────────────────
const C_TEXT    = "1a1c20";
const C_MUTED   = "555555";
const C_FAINT   = "999999";
const C_LINE    = "cccccc";
const C_RULE    = "1a1c20";
const C_CODE    = "444444";
const C_CODE_BG = "f0f0f0";

// ── Font stacks ───────────────────────────────────────────────────────────────
// Latin + CJK fallback; host must have fonts-liberation + fonts-noto-cjk.
const F_SERIF = `"Times New Roman", "Noto Serif CJK SC"`;
const F_SANS  = `"Arial", "Noto Sans CJK SC"`;
const F_MONO  = `"Courier New", "Noto Sans Mono CJK SC"`;

// ── Typst helper builders ─────────────────────────────────────────────────────

const rgb  = (c: string) => `rgb("${c}")`;
const fill = (c: string) => `fill: ${rgb(c)}`;
const font = (f: string) => `font: (${f})`;

function tx(opts: string, content: string): string {
  return `#text(${opts})[${content}]`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function renderDocumentTypst(document: DocumentModel, config: AppConfig): string {
  const meta = document.meta;
  const brand = resolveBrand(meta.brand.label, config);

  return [
    renderPreamble(meta, brand),
    renderCoverZone(meta, brand),
    renderBodyBlocks(document.content, document.assets, meta.docId),
  ].join("\n");
}

// ── Preamble ──────────────────────────────────────────────────────────────────

function renderPreamble(meta: DocumentModel["meta"], brand: { displayName: string }): string {
  const brandUpper = escStr(brand.displayName.toUpperCase());
  const docRef     = escStr([meta.docId, meta.version].filter(Boolean).join("  ·  "));

  return `\
// Generated by notion-doc-publisher-v3 — ${meta.docId}

// ── Page setup (US Letter) ────────────────────────────────────────────────────
#set page(
  paper: "us-letter",
  margin: (top: 1in, bottom: 1in, left: 1.25in, right: 1in),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(${font(F_SANS)}, size: 7.5pt)
      #grid(
        columns: (1fr, auto),
        align: horizon,
        text(weight: "bold", ${fill(C_TEXT)})["${brandUpper}"],
        text(size: 7pt, ${fill(C_MUTED)})["${docRef}"],
      )
      #v(1pt)
      #line(length: 100%, stroke: 0.5pt + ${rgb(C_LINE)})
    ]
  },
  footer: context [
    #line(length: 100%, stroke: 0.5pt + ${rgb(C_LINE)})
    #v(2pt)
    #set text(${font(F_SANS)}, size: 7.5pt, ${fill(C_MUTED)})
    #align(right)[Page #counter(page).display() of #counter(page).final().first()]
  ],
)

// ── Base typography ───────────────────────────────────────────────────────────
#set text(${font(F_SERIF)}, size: 11pt, ${fill(C_TEXT)}, lang: "en")
#set par(leading: 0.65em, spacing: 6pt, justify: true)

// ── Heading show rules ────────────────────────────────────────────────────────
#show heading.where(level: 1): it => [
  #v(18pt)
  #block(width: 100%, stroke: (bottom: 0.5pt + ${rgb(C_LINE)}), inset: (bottom: 3pt), below: 6pt)[
    #text(${font(F_SANS)}, size: 15pt, weight: "bold", ${fill(C_TEXT)})[#it.body]
  ]
]
#show heading.where(level: 2): it => [
  #v(12pt)
  #block(below: 4pt)[#text(${font(F_SANS)}, size: 13pt, weight: "bold", ${fill(C_TEXT)})[#it.body]]
]
#show heading.where(level: 3): it => [
  #v(10pt)
  #block(below: 3pt)[#text(${font(F_SANS)}, size: 11pt, weight: "bold", ${fill(C_TEXT)})[#it.body]]
]
#show heading.where(level: 4): it => [
  #v(8pt)
  #block(below: 2pt)[#text(${font(F_SANS)}, size: 10pt, weight: "bold", ${fill(C_MUTED)})[#it.body]]
]

// ── Code show rules ───────────────────────────────────────────────────────────
#show raw.where(block: true): it => block(
  fill: none,
  stroke: (left: 2pt + ${rgb(C_FAINT)}),
  inset: (left: 9pt, y: 6pt),
  width: 100%,
)[#text(${font(F_MONO)}, size: 9pt, ${fill(C_CODE)})[#it]]

#show raw.where(block: false): it => box(
  fill: ${rgb(C_CODE_BG)},
  inset: (x: 3pt, y: 1pt),
  radius: 2pt,
)[#text(${font(F_MONO)}, size: 9.5pt)[#it]]

// ── List styles ───────────────────────────────────────────────────────────────
#set list(marker: [•], body-indent: 12pt, spacing: 3pt)
#set enum(body-indent: 12pt, spacing: 3pt)

`;
}

// ── Cover zone ────────────────────────────────────────────────────────────────

function renderCoverZone(meta: DocumentModel["meta"], brand: { displayName: string; tagline: string }): string {
  const parts: string[] = [];

  // Masthead — brand (left) + tagline (right) with 2pt bottom rule
  const bName    = escContent(brand.displayName.toUpperCase());
  const bTagline = escContent(brand.tagline.toUpperCase());

  parts.push(`// ── Cover zone ────────────────────────────────────────────────────────────────
#block(width: 100%, stroke: (bottom: 2pt + ${rgb(C_RULE)}), inset: (bottom: 5pt))[
  #set text(${font(F_SANS)})
  #grid(
    columns: (1fr, auto),
    align: bottom,
    text(size: 11pt, weight: "bold", tracking: 1pt, ${fill(C_TEXT)})[${bName}],
    text(size: 7pt, weight: "bold", tracking: 0.5pt, ${fill(C_MUTED)})[${bTagline}],
  )
]`);

  // Type kicker
  if (meta.documentType.label) {
    const kicker = escContent(meta.documentType.label.toUpperCase());
    parts.push(`#v(10pt)\n${tx(`${font(F_SANS)}, size: 7.5pt, weight: "bold", ${fill(C_MUTED)}`, kicker)}`);
  }

  // Title
  parts.push(`#v(3pt)\n${tx(`${font(F_SANS)}, size: 20pt, weight: "bold", ${fill(C_TEXT)}`, escContent(meta.title))}`);

  // Identity line (top rule + DOC_ID · type · version · status)
  // Explicit font/size on every run — no top-level #set text that would bleed into body.
  const idF = `${font(F_SANS)}, size: 9pt`;
  const idSegs: string[] = [];
  const sep = tx(`${idF}, ${fill(C_FAINT)}`, "  ·  ");
  if (meta.docId)              idSegs.push(tx(`${idF}, weight: "bold", ${fill(C_TEXT)}`, escContent(meta.docId)));
  if (meta.documentType.label) idSegs.push(tx(`${idF}, ${fill(C_MUTED)}`, escContent(meta.documentType.label)));
  if (meta.version)            idSegs.push(tx(`${idF}, ${fill(C_MUTED)}`, `Version ${escContent(meta.version)}`));
  if (meta.status)             idSegs.push(tx(`${idF}, ${fill(C_MUTED)}`, escContent(meta.status)));

  const idLine = idSegs.join(sep);
  parts.push(`#v(6pt)\n#line(length: 100%, stroke: 0.5pt + ${rgb(C_LINE)})\n#v(2pt)\n${idLine}`);

  // Metadata strip — CLIENT / PROJECT
  const metaFields: Array<[string, string]> = ([
    ["CLIENT",  meta.client.label],
    ["PROJECT", meta.project.label],
  ] as Array<[string, string]>).filter(([, v]) => Boolean(v));

  if (metaFields.length > 0) {
    // Grid cells are content arguments — wrap in [...] so #text() is in content mode.
    const metaRows = metaFields.map(([label, value]) =>
      `  [${tx(`${font(F_SANS)}, size: 7.5pt, weight: "bold", ${fill(C_MUTED)}`, escContent(label))}],\n` +
      `  [${tx(`${font(F_SANS)}, size: 9pt, ${fill(C_TEXT)}`, escContent(value))}],`
    ).join("\n");
    parts.push(`#v(4pt)\n#grid(\n  columns: (72pt, 1fr),\n  row-gutter: 2pt,\n${metaRows}\n)`);
  }

  // Rule before body
  parts.push(`#v(8pt)\n#line(length: 100%, stroke: 0.5pt + ${rgb(C_LINE)})\n#v(8pt)\n`);

  return parts.join("\n");
}

// ── Body blocks ───────────────────────────────────────────────────────────────

function renderBodyBlocks(blocks: DocumentBlock[], assets: DocumentAsset[], docId: string): string {
  const parts: string[] = [];
  let i = 0;

  while (i < blocks.length) {
    const block = blocks[i];

    if (block.type === "bulleted_list_item") {
      const items: RichTextSpan[][] = [];
      while (i < blocks.length && blocks[i].type === "bulleted_list_item") {
        const b = blocks[i++];
        if (b.type === "bulleted_list_item") items.push(b.richText);
      }
      parts.push(items.map((rt) => `- ${renderRichText(rt)}`).join("\n"));
    } else if (block.type === "numbered_list_item") {
      const items: RichTextSpan[][] = [];
      while (i < blocks.length && blocks[i].type === "numbered_list_item") {
        const b = blocks[i++];
        if (b.type === "numbered_list_item") items.push(b.richText);
      }
      parts.push(items.map((rt) => `+ ${renderRichText(rt)}`).join("\n"));
    } else {
      parts.push(renderSingleBlock(blocks[i], assets, docId));
      i++;
    }
  }

  return parts.join("\n\n");
}

function renderSingleBlock(block: DocumentBlock, assets: DocumentAsset[], docId: string): string {
  switch (block.type) {
    case "paragraph":
      return renderRichText(block.richText) || " ";

    case "heading_1":   return `= ${renderRichText(block.richText)}`;
    case "heading_2":   return `== ${renderRichText(block.richText)}`;
    case "heading_3":   return `=== ${renderRichText(block.richText)}`;
    case "heading_4":   return `==== ${renderRichText(block.richText)}`;

    case "quote":
      return `#block(stroke: (left: 1pt + ${rgb(C_MUTED)}), inset: (left: 18pt, right: 6pt, y: 6pt), width: 100%)[#text(style: "italic", ${fill(C_MUTED)})[${renderRichText(block.richText)}]]`;

    case "callout":
      return `#block(stroke: 0.5pt + ${rgb(C_LINE)}, inset: 12pt, width: 100%)[${tx(`${font(F_SANS)}, size: 10.5pt`, renderRichText(block.richText))}]`;

    case "code": {
      const codeText = block.richText.map((s) => s.text).join("");
      const langPart = block.language ? `, lang: "${escStr(block.language)}"` : "";
      return `#raw(block: true${langPart}, "${escStr(codeText)}")`;
    }

    case "divider":
      return `#line(length: 100%, stroke: 0.5pt + ${rgb(C_LINE)})`;

    case "image":
      return renderImageBlock(block.asset, docId);

    case "file":
      return renderFileBlock(block.asset);

    case "table":
      return renderTableBlock(block.rows);

    case "unsupported":
      return `// [unsupported: ${block.notionType}]`;

    default:
      return "";
  }
}

// ── Rich text ─────────────────────────────────────────────────────────────────

export function renderRichText(spans: RichTextSpan[]): string {
  if (spans.length === 0) return "";

  return spans.map((span) => {
    if (span.code) {
      return `#raw("${escStr(span.text)}")`;
    }

    let content = escContent(span.text);

    if (span.bold && span.italic) {
      content = tx(`weight: "bold", style: "italic"`, content);
    } else if (span.bold) {
      content = tx(`weight: "bold"`, content);
    } else if (span.italic) {
      content = tx(`style: "italic"`, content);
    }

    if (span.underline) content = `#underline[${content}]`;
    if (span.strike)    content = `#strike[${content}]`;

    if (span.href) {
      content = `#link("${escStr(span.href)}")[${content}]`;
    }

    return content;
  }).join("");
}

// ── Image & file blocks ───────────────────────────────────────────────────────

function renderImageBlock(asset: DocumentAsset, docId: string): string {
  if (!asset.local || !asset.outputPath) {
    return `// [Image unavailable: ${asset.sourceUrl}]`;
  }

  const filename = asset.outputPath.split("/").pop();
  if (!filename) return `// [Image: missing filename]`;

  // .typ file is at dist/typst/{docId}.typ; image is at dist/assets/docs/{docId}/{filename}
  const relPath = `../assets/docs/${docId}/${filename}`;
  const caption = asset.caption?.map((s) => s.text).join("") || "";

  if (caption) {
    return `#figure(\n  image("${escStr(relPath)}", width: 100%),\n  caption: [${escContent(caption)}],\n)`;
  }

  return `#block(image("${escStr(relPath)}", width: 100%))`;
}

function renderFileBlock(asset: DocumentAsset): string {
  const filename = asset.outputPath?.split("/").pop() || asset.sourceUrl;
  return `${tx(`${font(F_SANS)}, size: 10pt`, `*File:* #link("${escStr(asset.sourceUrl)}")[${escContent(filename)}]`)}`;
}

// ── Table block ───────────────────────────────────────────────────────────────

function renderTableBlock(rows: RichTextSpan[][][]): string {
  if (rows.length === 0) return "";

  const colCount = rows.reduce((max, row) => Math.max(max, row.length), 0) || 1;
  const cols = Array<string>(colCount).fill("1fr").join(", ");

  const cellLines: string[] = [];
  for (let rowIdx = 0; rowIdx < rows.length; rowIdx++) {
    const row = rows[rowIdx];
    for (let colIdx = 0; colIdx < colCount; colIdx++) {
      const cell = row[colIdx] ?? [];
      const content = renderRichText(cell);
      if (rowIdx === 0) {
        cellLines.push(`  table.cell(fill: ${rgb("e8e8e8")})[${tx(`${font(F_SANS)}, size: 9.5pt, weight: "bold"`, content)}]`);
      } else {
        cellLines.push(`  [${tx(`${font(F_SANS)}, size: 9.5pt`, content)}]`);
      }
    }
  }

  return `#table(\n  columns: (${cols}),\n  stroke: 0.5pt + ${rgb(C_LINE)},\n  inset: (x: 6pt, y: 4pt),\n  align: left,\n${cellLines.join(",\n")},\n)`;
}

// ── Escaping ──────────────────────────────────────────────────────────────────

// For Typst string literals: "..."
function escStr(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

// For Typst content mode: [...]
function escContent(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/#/g, "\\#")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/`/g, "\\`")
    .replace(/@/g, "\\@")
    .replace(/\$/g, "\\$")
    .replace(/</g, "\\<")
    .replace(/~/g, "\\~");
}

// ── Brand resolution ──────────────────────────────────────────────────────────

type BrandPresentation = { displayName: string; tagline: string };

function resolveBrand(label: string, config: AppConfig): BrandPresentation {
  const profile: BrandProfile | undefined = config.brandProfiles[label];
  return {
    displayName: profile?.displayName?.trim() || label || "Document",
    tagline: profile?.tagline?.trim() || "",
  };
}
